// Copyright 2026 Aurora Emulator Project
// Licensed under GPLv2 or any later version
// Refer to the license.txt file included.

#pragma once

#include "common/serialization/compat.h"

#define SERIALIZATION_CLASS_EXPORT_KEY(...) SERIALIZATION_COMPAT_CLASS_EXPORT_KEY(__VA_ARGS__)
#define SERIALIZATION_CONSTRUCT(...) SERIALIZATION_COMPAT_CONSTRUCT(__VA_ARGS__)
#define SERIALIZATION_CLASS_VERSION(...) SERIALIZATION_COMPAT_CLASS_VERSION(__VA_ARGS__)
#define SERIALIZATION_SPLIT_MEMBER() SERIALIZATION_COMPAT_SPLIT_MEMBER()
#define SERIALIZATION_EXT_NAMESPACE_BEGIN SERIALIZATION_COMPAT_EXT_NAMESPACE_BEGIN
#define SERIALIZATION_EXT_NAMESPACE_END SERIALIZATION_COMPAT_EXT_NAMESPACE_END

namespace SerializationCompat = Common::SerializationCompat;
