platform :ios, '26.0'
use_frameworks!
inhibit_all_warnings!

target 'AuroraIOS' do
  pod 'boost'
  pod 'libzstd', '~> 1.5'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '26.0'
    end
  end
end
