name: AuroraSwift
options:
  deploymentTarget:
    iOS: "26.0"
configs:
  Debug: debug
  Release: release
schemes:
  Cytrus:
    build:
      targets:
        AuroraSwift: all
    run:
      config: Release
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
packages:
  zlib-spm:
    url: https://github.com/Azoy/zlib-spm
    branch: master
  zstd:
    url: https://github.com/jarrodnorwell/zstd
    branch: dev
  openssl:
    url: https://github.com/krzyzanowskim/OpenSSL
    branch: main
  SharedDependencies:
    path: ../SharedDependencies
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.auroraemu.auroraswift
    SWIFT_VERSION: 5.10
    SWIFT_OBJC_BRIDGING_HEADER: ../Platforms/AuroraIOS/swift/Bridge/AuroraSwift-Bridging-Header.h
    CLANG_CXX_LANGUAGE_STANDARD: gnu++20
    OTHER_CPLUSPLUSFLAGS:
      - "$(inherited)"
      - "-std=gnu++20"
    ENABLE_BITCODE: NO
    GCC_PREPROCESSOR_DEFINITIONS:
      - "$(inherited)"
      - "ENABLE_VULKAN=1"
      - "ENABLE_SOFTWARE_RENDERER=1"
    HEADER_SEARCH_PATHS:
      - "$(inherited)"
      - "$(SRCROOT)/../src"
      - "$(SRCROOT)/../src/core"
      - "$(SRCROOT)/../src/core/bridge_cores/aurora3ds"
      - "$(SRCROOT)/../src/core/bridge_cores/aurora3ds/Core/include"
      - "$(SRCROOT)/../Dependicies/Sources/cereal/include"
      - "$(SRCROOT)/../Dependicies/Sources/cryptopp/include"
      - "$(SRCROOT)/../Dependicies/Sources/dds_ktx/include"
      - "$(SRCROOT)/../Dependicies/Sources/eventbus/include"
      - "$(SRCROOT)/../Dependicies/Sources/glslang/include"
      - "$(SRCROOT)/../Dependicies/Sources/glib/include"
      - "$(SRCROOT)/../Dependicies/Sources/httplib/include"
      - "$(SRCROOT)/../Dependicies/Sources/inih/include"
      - "$(SRCROOT)/../Dependicies/Sources/jwt/include"
      - "$(SRCROOT)/../Dependicies/Sources/libchdr/include"
      - "$(SRCROOT)/../Dependicies/Sources/libslirp/include"
      - "$(SRCROOT)/../Dependicies/Sources/lodepng/include"
      - "$(SRCROOT)/../Dependicies/Sources/magic_enum/include"
      - "$(SRCROOT)/../Dependicies/Sources/metal_cpp/include"
      - "$(SRCROOT)/../Dependicies/Sources/microprofile/include"
      - "$(SRCROOT)/../Dependicies/Sources/miniz/include"
      - "$(SRCROOT)/../Dependicies/Sources/nihstro/include"
      - "$(SRCROOT)/../Dependicies/Sources/nlohmann/include"
      - "$(SRCROOT)/../Dependicies/Sources/oaknut/include"
      - "$(SRCROOT)/../Dependicies/Sources/boost/include"
      - "$(SRCROOT)/../Dependicies/Sources/vma/include"
      - "$(SRCROOT)/../Dependicies/Sources/stb/include"
      - "$(SRCROOT)/../Dependicies/Sources/toml/include"
      - "$(SRCROOT)/../Dependicies/Sources/tsl/include"
      - "$(SRCROOT)/../Dependicies/Sources/xxhash/include"
      - "$(SRCROOT)/../Dependicies/Sources/vulkan/include"
      - "$(SRCROOT)/../Platforms/API"
      - "$(SRCROOT)/../Platforms/AuroraIOS/objc"
    FRAMEWORK_SEARCH_PATHS:
      - "$(SRCROOT)/../Dependicies"
      - "$(inherited)"
    LIBRARY_SEARCH_PATHS:
      - "$(SRCROOT)/../Dependicies"
      - "$(inherited)"

targets:
  AuroraSwift:
    type: application
    platform: iOS
    info:
      path: ../Config/Info.plist
    entitlements:
      path: ../Config/Entitlements.plist
    sources:
      - path: ../Platforms/AuroraIOS/swift
      - path: ../Platforms/AuroraIOS/objc/Controllers/AUR3DSEmulatorViewController.h
      - path: ../Platforms/AuroraIOS/objc/Controllers/AUR3DSEmulatorViewController.mm
      - path: ../src/core/bridge_cores/aurora3ds
        excludes:
          - "**/*.md"
          - "**/*.txt"
    dependencies:
      - framework: ../Dependicies/MoltenVK.xcframework
      - framework: ../Dependicies/libavcodec.xcframework
      - framework: ../Dependicies/libavfilter.xcframework
      - framework: ../Dependicies/libavformat.xcframework
      - framework: ../Dependicies/libavutil.xcframework
      - framework: ../Dependicies/libswresample.xcframework
      - framework: ../Dependicies/libswscale.xcframework
      - package: SharedDependencies
        product: FLAC
      - package: SharedDependencies
        product: ogg
      - package: SharedDependencies
        product: lib_sdl3
      - package: SharedDependencies
        product: lib_boostcontext
      - package: SharedDependencies
        product: lib_boostiostreams
      - package: SharedDependencies
        product: lib_boostprogramoptions
      - package: SharedDependencies
        product: lib_boostserialization
      - package: SharedDependencies
        product: lib_dynarmic
      - package: SharedDependencies
        product: lib_enet
      - package: SharedDependencies
        product: lib_faad2
      - package: SharedDependencies
        product: lib_fmt
      - package: SharedDependencies
        product: lib_genericcodegen
      - package: SharedDependencies
        product: lib_glslang
      - package: SharedDependencies
        product: lib_machineindependent
      - package: SharedDependencies
        product: lib_mcl
      - package: SharedDependencies
        product: lib_openal
      - package: SharedDependencies
        product: lib_opus
      - package: SharedDependencies
        product: lib_sirit
      - package: SharedDependencies
        product: lib_soundtouch
      - package: SharedDependencies
        product: lib_spirv
      - package: SharedDependencies
        product: lib_teakra
      - package: zstd
        product: libzstd
      - package: zstd
        product: libseekable_format
      - package: openssl
        product: OpenSSL
    settings:
      base:
        INFOPLIST_FILE: ../Config/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
