#!/usr/bin/env python3
"""Vendor the minimal Crypto++ source subset used by aurora3ds.

This script scans aurora3ds sources for #include <cryptopp/...>, resolves
transitive Crypto++ internal includes, and copies only required headers/sources
from a local Crypto++ checkout.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import shutil
from collections import deque

INCLUDE_RE = re.compile(r"#\s*include\s*[\"<]([^\">]+)[\">]")


def find_entry_headers(aurora_root: pathlib.Path) -> set[str]:
    headers: set[str] = set()
    for path in aurora_root.rglob("*"):
        if path.suffix.lower() not in {".h", ".hpp", ".hh", ".c", ".cc", ".cpp", ".mm"}:
            continue
        text = path.read_text(errors="ignore")
        for m in re.finditer(r'#include\s*[<\"]cryptopp/([^>\"]+)[>\"]', text):
            headers.add(m.group(1))
    return headers


def collect_closure(crypto_root: pathlib.Path, entry_headers: set[str]) -> set[str]:
    available = {p.name for p in crypto_root.glob("*") if p.is_file()}
    needed: set[str] = set()
    q: deque[str] = deque(sorted(entry_headers))

    while q:
        rel = q.popleft()
        if rel in needed:
            continue
        file_path = crypto_root / rel
        if not file_path.exists():
            raise FileNotFoundError(f"Crypto++ file not found: {rel}")
        needed.add(rel)

        # Pull matching implementation unit when it exists.
        if rel.endswith(".h"):
            cpp = rel[:-2] + ".cpp"
            if cpp in available and cpp not in needed:
                q.append(cpp)

        text = file_path.read_text(errors="ignore")
        for match in INCLUDE_RE.finditer(text):
            inc = match.group(1)
            if "/" in inc:
                # External or nested include path.
                continue
            if inc in available and inc not in needed:
                q.append(inc)

    return needed


def write_manifest(out_dir: pathlib.Path, entry_headers: set[str], files: set[str]) -> None:
    manifest = out_dir / "VENDORED_FROM.txt"
    lines = [
        "Crypto++ minimal subset for aurora3ds",
        "",
        "Generated by scripts/vendor_cryptopp_minimal.py",
        "",
        "Entry headers detected from aurora3ds:",
        *[f"- {h}" for h in sorted(entry_headers)],
        "",
        f"Total files: {len(files)}",
        *[f"- {f}" for f in sorted(files)],
        "",
    ]
    manifest.write_text("\n".join(lines))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--aurora-root", default="src/core/aurora3ds")
    parser.add_argument("--crypto-root", required=True, help="Path to Crypto++ source root")
    parser.add_argument("--out-dir", default="src/core/aurora3ds/externals/cryptopp/cryptopp")
    args = parser.parse_args()

    aurora_root = pathlib.Path(args.aurora_root)
    crypto_root = pathlib.Path(args.crypto_root)
    out_dir = pathlib.Path(args.out_dir)

    entry_headers = find_entry_headers(aurora_root)
    files = collect_closure(crypto_root, entry_headers)

    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    for rel in sorted(files):
        shutil.copy2(crypto_root / rel, out_dir / rel)

    # Keep license at vendored root.
    for license_name in ["License.txt", "license.txt", "LICENSE"]:
        license_path = crypto_root / license_name
        if license_path.exists():
            shutil.copy2(license_path, out_dir / "LICENSE")
            break

    write_manifest(out_dir, entry_headers, files)
    print(f"Vendored {len(files)} files into {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
